### ISSUE TITLE
Crash game on 1.15.2

### ISSUE THREAD

**Issue by Kawazu0** [SR2610/MicroMods#12]
When a creeper explodes I get :

Time: 23/06/20 12:59
Description: Ticking entity

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.Entity.field_70165_t from class com.sr2610.creeperconfetti.ConfettiHandler
	at com.sr2610.creeperconfetti.ConfettiHandler.creeperExplodeEvent(ConfettiHandler.java:49) ~[?:2.1] {re:classloading}

> java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
> Forge version : 1.15.2-31.2.22

Regards.

**Comment by Kawazu0** [comment]
I built 3.0 (openjdk on debian) tried on Windows because I forgot to download 1.15.2 on linux and got this :
(I don't know if it can help)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.CreeperEntity)
	Entity ID: 5
	Entity Name: Creeper
	Entity's Exact location: 178.77, 64.00, -261.86
	Entity's Block location: World: (178,64,-262), Chunk: (at 2,4,10 in 11,-17; contains blocks 176,0,-272 to 191,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1072191888 bytes (1022 MB) / 2248146944 bytes (2144 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.22.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.22
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.22-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.22-universal.jar Forge {forge@31.2.22 DONE}
		creepercontetti-3.0.jar Creeper Confetti {creeperconfetti@3.0 DONE}
	Player Count: 0 / 8; []
	Data Packs: mod:forge (incompatible), mod:creeperconfetti (incompatible), vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by SR2610** [comment]
The mod isn't officially supported for 1.15.2 yet so closing the issue.
