### ISSUE TITLE
Server Crash 1.16.1 | creeperconfetti 3.2

### ISSUE THREAD

**Issue by plenet10** [SR2610/MicroMods#13]
Hi,

I was running it on my server and then it happened my server went down, we found the issue to be unfortunately with Creeper confetti. The Server is running Forge 32.0.98. 

If you need more info please ask.
[crash-2020-08-03_18.15.52-server.txt](https://github.com/SR2610/MicroMods/files/5017997/crash-2020-08-03_18.15.52-server.txt)

**Comment by SR2610** [comment]
Thanks for reporting this and attaching a crash log. Do you have any of the config options changed or is this with the default settings?

**Comment by plenet10** [comment]
I have Changed the damagePlayers option to true

**Comment by SR2610** [comment]
Alright I'll have a play around and see if I can fix this.  I may not have tested that option enough.  Thanks for the quick response.

**Comment by SR2610** [comment]
This issue has been fixed in version 3.3.  I've [uploaded it to curseforge](https://www.curseforge.com/minecraft/mc-mods/creeper-confetti/files/3022658) and just waiting on their approval which should be quite quick.  Thanks for reporting this and let me know if you find any more issues.
