### ISSUE TITLE
Creeper Confetti 1.16.2+ Incompatibility 

### ISSUE THREAD

**Issue by ChloeDawn** [SR2610/MicroMods#14]
As of 1.16.2, Forge requires mods to declare their license metadata. Creeper Confetti 3.3 causes Forge to crash the game at startup due to lack of this.

**Comment by SR2610** [comment]
Yeah I'm aware of this.  The mod isn't marked as compatible for these versions yet and needs doing.  Should get it done in the next couple of days.

**Comment by SR2610** [comment]
Fixed this with the latest commit.  New version on Curseforge compatible with 1.16.3.  If the need is there I may make a dedicated fix for 1.16.2 as well.
