### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by EduBRz** [SR2610/MicroMods#2]
ERROR The mcmod.info file in CreeperConfetti-1.0.jar cannot be parsed as valid JSON. It will be ignored
14.07 12:13:18 [Server] INFO com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 4 column 14
14.07 12:13:18 [Server] INFO at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:55) [MetadataCollection.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [JarDiscoverer.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:133) [ModDiscoverer.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) [FMLCommonHandler.class:1.7.10-1614.58]
14.07 12:13:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) [lt.class:?]
14.07 12:13:18 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
14.07 12:13:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
14.07 12:13:18 [Server] INFO Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 4 column 14
14.07 12:13:18 [Server] INFO at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480) ~[JsonReader.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[TypeAdapters$25.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659) ~[TypeAdapters$25.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
14.07 12:13:18 [Server] INFO at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
14.07 12:13:18 [Server] INFO ... 14 more

**Comment by SR2610** [comment]
Only happened in this one scenario, not a bug with the mod.
